apiVersion: v1
kind: Pod
metadata:
  name: pod-w-message
spec:
  restartPolicy: Never
  containers:
  - name: messager
    image: "centos:7"
    command: ["/bin/sh","-c"]
    args: ["sleep 60 && /bin/echo Sleep expired > /dev/termination-log"]
