apiVersion: v1
kind: Pod
metadata:
  labels:
    name: influxdb
  name: influxdb
spec:
  volumes:
    - name: "influxdb-data"
      gcePersistentDisk:
        pdName: influxdb
        fsType: ext4
  containers:
    - image: docker.io/tutum/influxdb:latest
      name: influxdb
      volumeMounts:
        - mountPath: "/data"
          name: "influxdb-data"
      resources:
        limits:
          cpu: "500m"
          memory: "128Mi"
      readinessProbe:
        httpGet:
          path: /ping
          port: 8086
        initialDelaySeconds: 5
        timeoutSeconds: 1
      livenessProbe:
        httpGet:
          path: /ping
          port: 8086
        initialDelaySeconds: 15
        timeoutSeconds: 1
      ports:
        - containerPort: 8083
          name: admin
          protocol: TCP
        - containerPort: 8086
          name: http
          protocol: TCP